### ISSUE TITLE
[spacemacs] treemacs icons are not sized properly 

### ISSUE THREAD

**Issue by ngortheone** [remacs/remacs#1513]
Icons in treemacs are not resized properly and always appear very small.
Repro: 
* Open treemacs - observe small icons
* eval `treemacs-resize-icons` with any given size - no visible effect

This is definitely a regression in Remacs, since both Emacs 26.2 and 27.0 compiled locally with the same `.emacs.d` folder do not have this problem

Remacs:
![DeepinScreenshot_select-area_20190608201732](https://user-images.githubusercontent.com/18271144/59153980-afde6c00-8a35-11e9-9e11-defddf258514.png)
Emacs:
![DeepinScreenshot_select-area_20190608201724](https://user-images.githubusercontent.com/18271144/59153981-afde6c00-8a35-11e9-840f-69521f91df0c.png)

**Comment by shaleh** [comment]
In rust_src/admin are scripts for running git bisect. You could use it to find the revision that caused it.

**Comment by ngortheone** [comment]
I already tried going back as far as June 2017 - it was still broken then. Can't go back even further, there is no recorded rust version required, build fails with random rust compilation errors

**Comment by ngortheone** [comment]
There was some development at https://github.com/Alexander-Miller/treemacs/issues/454
It appears that remacs does not have imagemagic support, and I tried configuring it with `--with-imagemagic` but it istill says:

```
Does Emacs use imagemagick (version 6)?                 no
```

**Comment by shaleh** [comment]
https://github.com/remacs/remacs/blob/c1555673a7d79453f8f450e4a3272fa4220d04b4/configure.ac#L2529

This looks like something waiting to be backported from current emacs. if it is small, you can try teasing the code out and preparing a PR. Otherwise, patience....

**Comment by shaleh** [comment]
I dropped the bug label. We simply do not support it yet.

**Comment by ngortheone** [comment]
I have tested `emacs-git` (27.0.50) and it has imagemagic disabled, but icon resizing still works. There must be something else that we are missing.

**Comment by ngortheone** [comment]
I decided to take a look at `treemacs--created-icons` variable and I found noticeable differences. (See snippet below)
1. `#70=(image` vs `#1=(image` 
There are 70 icons in the list. And each icon has its own number. Previous icon has `#69` in Emacs.
In Remacs they are all `#1`
2. The order of the elements inside icon list is reversed. Emacs has:
 `(propertize " " 'display image-unselected 'img-selected image-selected 'img-unselected image-unselected)`
but Remacs has it it reverse order
3. Probably irrelevant, but anyway - background property values are different

Here is the last item from the list of icons:
* Emacs
```lisp
#(  "  " 
    0 
    1
    (display 
    #70=(image 
           :type png 
           :file "/home/ngor/.emacs.d/elpa/27.0/develop/treemacs-20190601.2254/icons/dir_closed.png" 
           :scale 2.3036144578313253 
           :ascent center 
           :background #2# 
           :height 40 
           :width 40)
    img-selected
    (image 
      :type png 
      :file "/home/ngor/.emacs.d/elpa/27.0/develop/treemacs-20190601.2254/icons/dir_closed.png" 
      :scale 2.3036144578313253 
      :ascent center 
      :background #3# 
      :height 40 
      :width 40)
    img-unselected 
    #70#))
```

* Remacs
```
  #("  " 0 1
    (img-unselected 
    #1=(image 
          :type png 
          :file "/home/ngor/.emacs.d/elpa/27.0/develop/treemacs-20190601.2254/icons/dir_closed.png" 
          :scale 2.3036144578313253 
          :ascent center 
          :background "#fbf8ef" 
          :height 40 
          :width 40)
    img-selected
    (image 
      :type png 
      :file "/home/ngor/.emacs.d/elpa/27.0/develop/treemacs-20190601.2254/icons/dir_closed.png" 
      :scale 2.3036144578313253 
      :ascent center 
      :background "#efeae9" 
      :height 40 
      :width 40)
    display 
    #1#)))
```

**Comment by ngortheone** [comment]
Alright. I am closing this one.
I removed imagemagic from my system for this experiment.
I can reproduce the issue on vanilla 26.2 emacs without imagemagic. So this is definitely not a Remacs problem.  

Interesting fact is that vanilla emacs 27.0.50 does not have this problem. Apparently there was something done to improve PNG image handling. Patches that we will have to port some day...

**Comment by ngortheone** [comment]
The confusion was added by the fact that Arch's emacs package has statically linked imagemagic support, but remacs build did not.
